# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "FrogBoardL"
product_name = "FrogNotReisL"
vendor_id = 0x4c4b
product_id = 0x464c
manufacturer = "haobo"
chip = "rp2040"
usb_enable = true
[matrix]
# ROWS (4 pins)
# Original: GP29, GP28, GP10, GP26
output_pins = ["PIN_29", "PIN_28", "PIN_10", "PIN_26"] 

# COLUMNS (7 pins)
# Original: GP15, GP14, GP12, GP13, GP27, GP11, GP6
input_pins = ["PIN_15", "PIN_14", "PIN_12", "PIN_13", "PIN_27", "PIN_11", "PIN_6"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 4
cols = 7
layers = 2
keymap = [
    # LAYER 0: Base Layer (Must have 4 rows x 7 columns)
    [
        ["A", "B", "C", "D", "E", "F", "_"],
        ["A", "B", "C", "D", "E", "F", "_"],
        ["A", "B", "C", "D", "E", "F", "G"],
        ["_", "_", "_", "_", "A", "B", "C"]
    ]
]
[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
